SeExprBuildins.cpp: Avoid ambiguous operator overloading
i686-apple-darwin11-llvm-g++-4.2 (GCC) 4.2.1
(Based on Apple Inc. build 5658) (LLVM build 2336.9.00)
from Mac OS X Lion, and possibly others, fail to build
due to expressions that contain ambiguous overloaded operators.

	.../src/SeExpr/SeExprBuiltins.cpp:596:28:
	      error: use of overloaded operator '+' is ambiguous
	      (with operand types 'SeVec3d' and 'double')
	return .5*vnoise(p)+.5;
	       ~~~~~~~~~~~~^~~

	.../src/SeExpr/SeExprBuiltins.cpp:857:65:
	      error: use of overloaded operator '-' is ambiguous
	      (with operand types 'SeVec3d' and 'double')
	...data.points[n] = testcell + jitter * (ccellnoise(testcell - .5));
	                                                    ~~~~~~~~ ^ ~~
Use SeVec3d(double) in these expressions to avoid ambiguities.